#!/bin/bash
#
FC='ftn'
F90C='ftn'
CC'cc'

DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI'
CPP='cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'

INCLUDES='-I/opt/cray/pe/mpt/7.7.10/gni/mpich-intel/16.0/include'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FFLAGS="$FFLAGS -g -convert big_endian -assume byterecl"
    FOPTIM='-O3 -align'
else
    FOPTIM='-O0 -noalign'
    FFLAGS="$FFLAGS -W0 -WB -xN -pc64 -convert big_endian -assume byterecl"
fi
